// Maps normalized team name variants → ESPN CDN abbreviation
// Logo URL: https://a.espncdn.com/i/teamlogos/nba/500/{abbr}.png
// All abbreviations verified working (200 OK) against ESPN CDN
const ABBR: Record<string, string> = {
  // ── Full names ──────────────────────────────────────────────
  'atlanta hawks': 'atl',
  'boston celtics': 'bos',
  'brooklyn nets': 'bkn',
  'charlotte hornets': 'cha',
  'chicago bulls': 'chi',
  'cleveland cavaliers': 'cle',
  'dallas mavericks': 'dal',
  'denver nuggets': 'den',
  'detroit pistons': 'det',
  'golden state warriors': 'gs',
  'houston rockets': 'hou',
  'indiana pacers': 'ind',
  'los angeles clippers': 'lac',
  'los angeles lakers': 'lal',
  'la clippers': 'lac',
  'la lakers': 'lal',
  'memphis grizzlies': 'mem',
  'miami heat': 'mia',
  'milwaukee bucks': 'mil',
  'minnesota timberwolves': 'min',
  'new orleans pelicans': 'no',
  'new york knicks': 'ny',
  'oklahoma city thunder': 'okc',
  'orlando magic': 'orl',
  'philadelphia 76ers': 'phi',
  'phoenix suns': 'phx',
  'portland trail blazers': 'por',
  'sacramento kings': 'sac',
  'san antonio spurs': 'sa',
  'toronto raptors': 'tor',
  'utah jazz': 'utah',
  'washington wizards': 'wsh',
  // ── Nicknames ───────────────────────────────────────────────
  'hawks': 'atl',
  'celtics': 'bos',
  'nets': 'bkn',
  'hornets': 'cha',
  'bulls': 'chi',
  'cavaliers': 'cle',
  'cavs': 'cle',
  'mavericks': 'dal',
  'mavs': 'dal',
  'nuggets': 'den',
  'pistons': 'det',
  'warriors': 'gs',
  'rockets': 'hou',
  'pacers': 'ind',
  'clippers': 'lac',
  'lakers': 'lal',
  'grizzlies': 'mem',
  'grizz': 'mem',
  'heat': 'mia',
  'bucks': 'mil',
  'timberwolves': 'min',
  'wolves': 'min',
  'pelicans': 'no',
  'knicks': 'ny',
  'thunder': 'okc',
  'magic': 'orl',
  '76ers': 'phi',
  'sixers': 'phi',
  'suns': 'phx',
  'trail blazers': 'por',
  'blazers': 'por',
  'kings': 'sac',
  'spurs': 'sa',
  'raptors': 'tor',
  'jazz': 'utah',
  'wizards': 'wsh',
  // ── City / state only ────────────────────────────────────────
  'atlanta': 'atl',
  'boston': 'bos',
  'brooklyn': 'bkn',
  'charlotte': 'cha',
  'chicago': 'chi',
  'cleveland': 'cle',
  'dallas': 'dal',
  'denver': 'den',
  'detroit': 'det',
  'golden state': 'gs',
  'houston': 'hou',
  'indiana': 'ind',
  'memphis': 'mem',
  'miami': 'mia',
  'milwaukee': 'mil',
  'minnesota': 'min',
  'new orleans': 'no',
  'new york': 'ny',
  'oklahoma city': 'okc',
  'oklahoma': 'okc',
  'orlando': 'orl',
  'philadelphia': 'phi',
  'phoenix': 'phx',
  'portland': 'por',
  'sacramento': 'sac',
  'san antonio': 'sa',
  'toronto': 'tor',
  'utah': 'utah',
  'washington': 'wsh',
  // ── Hebrew team name variants ────────────────────────────────
  // Full Hebrew names
  'אטלנטה הוקס': 'atl',
  'בוסטון סלטיקס': 'bos',
  'בוסטון קלטיקס': 'bos',
  'ברוקלין נטס': 'bkn',
  'שרלוט הורנטס': 'cha',
  'שיקגו בולס': 'chi',
  'קליבלנד קבליירס': 'cle',
  'דאלאס מאברקס': 'dal',
  'דנבר נאגטס': 'den',
  'דטרויט פיסטונס': 'det',
  'גולדן סטייט ווריורס': 'gs',
  'הוסטון רוקטס': 'hou',
  'אינדיאנה פייסרס': 'ind',
  'לוס אנג\'לס קליפרס': 'lac',
  'לוס אנג\'לס לייקרס': 'lal',
  'ממפיס גריזליס': 'mem',
  'מיאמי היט': 'mia',
  'מילווקי באקס': 'mil',
  'מינסוטה טימברוולבס': 'min',
  'מינסוטה טימבר וולבס': 'min',
  'ניו אורלינס פליקנס': 'no',
  'ניו יורק ניקס': 'ny',
  'אוקלהומה סיטי תאנדר': 'okc',
  'אורלנדו מג\'יק': 'orl',
  'פילדלפיה 76\'רס': 'phi',
  'פניקס סאנס': 'phx',
  'פורטלנד טריל בלייזרס': 'por',
  'סקרמנטו קינגס': 'sac',
  'סן אנטוניו ספארס': 'sa',
  'טורונטו ראפטורס': 'tor',
  'יוטה ג\'אז': 'utah',
  'וושינגטון וויזארדס': 'wsh',
  // Hebrew nicknames only
  'הוקס': 'atl',
  'סלטיקס': 'bos',
  'קלטיקס': 'bos',
  'נטס': 'bkn',
  'הורנטס': 'cha',
  'בולס': 'chi',
  'קבליירס': 'cle',
  'קבס': 'cle',
  'מאברקס': 'dal',
  'מאוורקס': 'dal',
  'נאגטס': 'den',
  'פיסטונס': 'det',
  'ווריורס': 'gs',
  'וורירס': 'gs',
  'רוקטס': 'hou',
  'פייסרס': 'ind',
  'קליפרס': 'lac',
  'לייקרס': 'lal',
  'גריזליס': 'mem',
  'היט': 'mia',
  'באקס': 'mil',
  'וולבס': 'min',
  'פליקנס': 'no',
  'ניקס': 'ny',
  'תאנדר': 'okc',
  'מג\'יק': 'orl',
  'מאג\'יק': 'orl',
  'סיקסרס': 'phi',
  'סאנס': 'phx',
  'בלייזרס': 'por',
  'קינגס': 'sac',
  'ספארס': 'sa',
  'ראפטורס': 'tor',
  'רפטורס': 'tor',
  'ג\'אז': 'utah',
  'וויזארדס': 'wsh',
  // Hebrew city/state names
  'אטלנטה': 'atl',
  'בוסטון': 'bos',
  'ברוקלין': 'bkn',
  'שרלוט': 'cha',
  'שיקגו': 'chi',
  'קליבלנד': 'cle',
  'דאלאס': 'dal',
  'דנבר': 'den',
  'דטרויט': 'det',
  'גולדן סטייט': 'gs',
  'הוסטון': 'hou',
  'אינדיאנה': 'ind',
  'ממפיס': 'mem',
  'מיאמי': 'mia',
  'מילווקי': 'mil',
  'מינסוטה': 'min',
  'אורלנדו': 'orl',
  'פילדלפיה': 'phi',
  'פניקס': 'phx',
  'פורטלנד': 'por',
  'סקרמנטו': 'sac',
  'סן אנטוניו': 'sa',
  'טורונטו': 'tor',
  'יוטה': 'utah',
  'וושינגטון': 'wsh',
  'אוקלהומה': 'okc',
  'ניו יורק': 'ny',
  'ניו אורלינס': 'no',
  // ── Standard 3-letter abbreviations ─────────────────────────
  'atl': 'atl',
  'bos': 'bos',
  'bkn': 'bkn',
  'cha': 'cha',
  'chi': 'chi',
  'cle': 'cle',
  'dal': 'dal',
  'den': 'den',
  'det': 'det',
  'gsw': 'gs',
  'gs': 'gs',
  'hou': 'hou',
  'ind': 'ind',
  'lac': 'lac',
  'lal': 'lal',
  'mem': 'mem',
  'mia': 'mia',
  'mil': 'mil',
  'min': 'min',
  'nop': 'no',
  'nor': 'no',
  'no': 'no',
  'nyk': 'ny',
  'ny': 'ny',
  'okc': 'okc',
  'orl': 'orl',
  'phi': 'phi',
  'phx': 'phx',
  'por': 'por',
  'sac': 'sac',
  'sas': 'sa',
  'sa': 'sa',
  'tor': 'tor',
  'uta': 'utah',
  'was': 'wsh',
  'wsh': 'wsh',
}

export function getTeamLogoUrl(name: string): string | null {
  if (!name || name === '-') return null
  const key = name.toLowerCase().trim()

  // 1. Exact match
  const abbr = ABBR[key]
  if (abbr) return `https://a.espncdn.com/i/teamlogos/nba/500/${abbr}.png`

  // 2. Word-by-word fallback — handles "OKC Thunder", "Golden State", etc.
  for (const word of key.split(/[\s_-]+/)) {
    const wa = ABBR[word]
    if (wa) return `https://a.espncdn.com/i/teamlogos/nba/500/${wa}.png`
  }

  return null
}
